language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

after_success:
  - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
  - julia --project=coverage/ coverage/coverage.jl

